USE ROLE ACCOUNTADMIN;

-- Allow cross-region access for Cortex to access all models
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Use Database for AI Development
USE SCHEMA AI_DEVELOPMENT.PUBLIC;

-- Create External Access for AI developer
CREATE OR REPLACE NETWORK RULE ai_external_access_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('0.0.0.0:80', '0.0.0.0:443');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ai_external_access_integration
  ALLOWED_NETWORK_RULES = (ai_external_access_rule)
  ENABLED = true;

-- Create role for AI engineer
CREATE ROLE IF NOT EXISTS AI_ENGINEER;
GRANT ROLE AI_ENGINEER to USER ADMIN;

-- Grant privileges to AI engineer role
GRANT USAGE, MONITOR, CREATE SCHEMA ON DATABASE AI_DEVELOPMENT TO ROLE AI_ENGINEER;
GRANT ALL ON SCHEMA AI_DEVELOPMENT.PUBLIC TO ROLE AI_ENGINEER;
GRANT ALL ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE AI_ENGINEER;
GRANT ALL ON COMPUTE POOL SYSTEM_COMPUTE_POOL_GPU TO ROLE AI_ENGINEER;
GRANT ALL ON WAREHOUSE AI_WH TO ROLE AI_ENGINEER;
GRANT USAGE ON INTEGRATION ai_external_access_integration TO ROLE AI_ENGINEER;

-- Grant privilege to use Cortex Functions
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE AI_ENGINEER;

-- Grant privileges to use PyPi packages
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE AI_ENGINEER;

-- Grant privileges to use GitHub repository
GRANT READ ON GIT REPOSITORY GITHUB_REPO_SYNTHETIC_DATA_GENERATION TO ROLE AI_ENGINEER;

-- Create notebooks
USE ROLE AI_ENGINEER;
CREATE OR REPLACE SCHEMA IF NOT EXISTS AI_DEVELOPMENT.SYNTHETIC_DATA_GENERATION;
USE SCHEMA AI_DEVELOPMENT.SYNTHETIC_DATA_GENERATION;

CREATE STAGE AUDIO
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE STAGE IMAGES
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE STAGE VIDEOS
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

-- Create Notebooks
CREATE OR REPLACE NOTEBOOK SYNTHETIC_DATA_GENERATION_AUDIO
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SYNTHETIC_DATA_GENERATION/branches/main/src' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_GPU'
        RUNTIME_NAME = 'SYSTEM$GPU_RUNTIME'
        MAIN_FILE = 'SYNTHETIC_DATA_GENERATION_AUDIO.ipynb';
ALTER NOTEBOOK SYNTHETIC_DATA_GENERATION_AUDIO ADD LIVE VERSION FROM LAST;

CREATE OR REPLACE NOTEBOOK food_beverage_call_center_recordings
    FROM '@AI_DEVELOPMENT.PUBLIC.GITHUB_REPO_SYNTHETIC_DATA_GENERATION/branches/main/src' 
        QUERY_WAREHOUSE = 'AI_WH'
        EXTERNAL_ACCESS_INTEGRATIONS = ('ai_external_access_integration')
        COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_GPU'
        RUNTIME_NAME = 'SYSTEM$GPU_RUNTIME'
        MAIN_FILE = 'notebooks/food_beverage_call_center_recordings.ipynb';
ALTER NOTEBOOK food_beverage_call_center_recordings ADD LIVE VERSION FROM LAST;